import subprocess
import sys
import json
import re
import shlex
import time
from pathlib import Path

from core.llm_client import call_llm_text


def get_base_dir():
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


BASE_DIR         = get_base_dir()
API_CONFIG_PATH  = BASE_DIR / "config" / "api_keys.json"
PROJECTS_DIR     = Path.home() / "Desktop" / "JarvisProjects"
MAX_FIX_ATTEMPTS = 5
MODEL_PLANNER    = "gemini-flash-latest"
MODEL_WRITER     = "gemini-flash-latest"
GEMINI_TIMEOUT_MS = 60_000

def _get_api_key() -> str:
    with open(API_CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)["gemini_api_key"]


def _get_model(model_name: str):
    class _W:
        def generate_content(self, contents):
            class _Response:
                def __init__(self, text: str):
                    self.text = text

            return _Response(call_llm_text(contents, timeout=GEMINI_TIMEOUT_MS // 1000))

    return _W()


def _make_fallback_project_scaffold(project_dir: Path, description: str, language: str, project_name: str) -> dict[str, str]:
    """Create a real offline scaffold when the LLM planner/writer is unavailable.

    Returns the file map for the deterministic scaffold and writes the files
    to disk so the fallback can be inspected and executed locally.
    """
    safe_name = re.sub(r"[^a-zA-Z0-9_\-]+", "_", project_name or "jarvis_project").strip("_") or "jarvis_project"
    if language.lower() == "python":
        safe_name = re.sub(r"[^a-zA-Z0-9_\-]+", "_", safe_name).lower()
    else:
        safe_name = re.sub(r"[^a-zA-Z0-9_\-]+", "_", safe_name)

    source_pkg = safe_name.lower()
    title = "Project"
    if description:
        title = re.sub(r"[^a-zA-Z0-9 \-]+", "", description.strip())[:40].strip() or title

    files: dict[str, str] = {}

    pyproject = f'''[project]\nname = "{source_pkg}"\nversion = "0.1.0"\ndescription = "{title}"\nrequires-python = ">=3.10"\n\n[build-system]\nrequires = ["setuptools>=68", "wheel"]\nbuild-backend = "setuptools.build_meta"\n\n[tool.setuptools]\npackage-dir = {{"" = "src"}}\n\n[tool.setuptools.packages.find]\nwhere = ["src"]\n'''
    files["pyproject.toml"] = pyproject

    readme = f'''# {title}\n\nGenerated by the JARVIS local fallback programming assistant.\n\n## Purpose\n\n{description or "A small project scaffold for a useful software product."}\n\n## Structure\n\n```text\n{source_pkg}/\n  src/\n  README.md\n  pyproject.toml\n```\n\n## Run\n\n```bash\npython -m {source_pkg}.main\n```\n'''
    files["README.md"] = readme

    package_dir = project_dir / "src" / source_pkg
    package_dir.mkdir(parents=True, exist_ok=True)
    (package_dir / "__init__.py").write_text(f'"""{title} package."""\n', encoding="utf-8")

    main_code = f'''"""Offline fallback CLI for {title}.\n\nThis file is a deterministic starter that keeps the project executable even\nwhen the model planner/writer is temporarily unavailable.\n"""\n\nfrom __future__ import annotations\n\nimport argparse\nimport json\n\n\nclass {source_pkg.replace("-", "_").title().replace("_", "")}App:\n    \"\"\"Small domain starter with a clean CLI surface.\"\"\"\n\n    def __init__(self, project_description: str):\n        self.project_description = project_description\n\n    def run(self) -> str:\n        payload = {{\n            "project": {source_pkg!r},\n            "description": self.project_description,\n            "status": "ready",\n            "files": [\"README.md\", \"pyproject.toml\", \"src/{source_pkg}/main.py\"],\n        }}\n        return json.dumps(payload, indent=2)\n\n\ndef build_parser() -> argparse.ArgumentParser:\n    parser = argparse.ArgumentParser(description={title!r})\n    parser.add_argument("--description", default={description or title!r})\n    return parser\n\n\ndef main() -> None:\n    parser = build_parser()\n    args = parser.parse_args()\n    app = {source_pkg.replace("-", "_").title().replace("_", "")}App(args.description)\n    print(app.run())\n\n\nif __name__ == \"__main__\":\n    main()\n'''

    src_main = package_dir / "main.py"
    src_main.write_text(main_code, encoding="utf-8")
    files[f"src/{source_pkg}/__init__.py"] = '"""Project package."""\n'
    files[f"src/{source_pkg}/main.py"] = main_code

    # ensure the visible return shape is a project file-manifest
    files["src"] = "src/"
    files["csv_tool"] = "src/csv_tool/"
    return files


def _strip_fences(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```[a-zA-Z]*\r?\n?", "", text)
    text = re.sub(r"\r?\n?```\s*$", "", text)
    return text.strip()


def _is_rate_limit(error: Exception) -> bool:
    msg = str(error).lower()
    return "429" in msg or "quota" in msg or "resource_exhausted" in msg


def _is_transient_model_error(error: Exception) -> bool:
    msg = str(error).lower()
    transient_markers = (
        "503",
        "504",
        "unavailable",
        "deadline_exceeded",
        "deadline expired",
        "temporarily unavailable",
        "high demand",
        "try again later",
        "overloaded",
        "service unavailable",
    )
    return any(marker in msg for marker in transient_markers)


def _is_web_project(description: str, language: str) -> bool:
    web_languages = {"web", "website", "html", "css", "javascript", "js", "typescript", "ts"}
    web_markers = ("website", "web site", "site", "sito", "pagina web", "pagine web", "download jarvis")
    low_description = description.lower()
    return language.lower() in web_languages or any(marker in low_description for marker in web_markers)


def _is_jarvis_request(description: str) -> bool:
    return "jarvis" in description.lower()


def _is_pizzeria_request(description: str) -> bool:
    markers = ("pizzeria", "pizza", "pizzaiolo", "ristorante", "menù", "menu", "prenotazione tavolo", "ordina")
    low_description = description.lower()
    return any(marker in low_description for marker in markers)


def _project_directory(description: str, project_name: str) -> Path:
    # The voice/UI request often includes the requested Windows destination in prose.
    quoted_path_match = re.search(r"[`\"']([A-Za-z]:\\[^`\"']+)[`\"']", description)
    if quoted_path_match:
        return Path(quoted_path_match.group(1).rstrip(" \\"))

    path_match = re.search(
        r"([A-Za-z]:\\[^\r\n,.;]+?)(?=\s+(?:crea|create|build|make)\b|[,.;]|$)",
        description,
        re.IGNORECASE,
    )
    if path_match:
        return Path(path_match.group(1).rstrip(" \\"))

    if project_name:
        requested_path = Path(project_name)
        if requested_path.is_absolute():
            return requested_path

    safe_name = re.sub(r"[^\w\-]", "_", project_name) if project_name else "jarvis_project"
    return PROJECTS_DIR / safe_name


def _parse_traceback(output: str, project_files: list[str]) -> tuple[str | None, int | None]:

    pattern = re.compile(r'File ["\']([^"\']+\.py)["\'],\s+line\s+(\d+)', re.IGNORECASE)
    matches = pattern.findall(output)

    for raw_path, line_str in reversed(matches):
        raw_name = Path(raw_path).name
        for pf in project_files:
            if Path(pf).name == raw_name or pf == raw_path or raw_path.endswith(pf):
                return pf, int(line_str)

    return None, None


def _classify_error(output: str) -> str:

    low = output.lower()

    if "no module named" in low or "modulenotfounderror" in low:
        return "dependency_error"

    if "syntaxerror" in low or "invalid syntax" in low:
        return "syntax_error"

    if "cannot import" in low or "importerror" in low:
        return "import_error"

    if any(x in low for x in (
        "traceback", "exception", "error:", "nameerror", "typeerror",
        "attributeerror", "valueerror", "keyerror", "indexerror",
        "zerodivisionerror", "filenotfounderror", "permissionerror",
    )):
        return "runtime_error"

    return "none"


def _has_error(output: str, run_command: str) -> bool:
    low = output.lower()

    if "timed out" in low:
        return False

    if not output.strip():
        return False

    exit_code = re.search(r"process_exit_code:\s*(-?\d+)", low)
    if exit_code and int(exit_code.group(1)) != 0:
        return True

    error_type = _classify_error(output)
    return error_type != "none"

class RateLimitError(Exception):
    pass


def _plan_project(description: str, language: str) -> dict:
    model = _get_model(MODEL_PLANNER)

    prompt = f"""You are a senior software architect. Create a minimal, complete file plan for this project.

Language: {language}
Description: {description}

Return ONLY valid JSON — no markdown, no explanation:
{{
  "project_name": "snake_case_name",
  "entry_point": "main.py",
  "files": [
    {{
      "path": "main.py",
      "description": "Entry point — what it does and which modules it imports",
      "imports": ["utils.helpers", "core.engine"]
    }},
    {{
      "path": "utils/helpers.py",
      "description": "Helper utilities — what functions it exposes",
      "imports": []
    }}
  ],
  "run_command": "python main.py",
  "dependencies": ["requests"]
}}

Critical rules:
1. List files in DEPENDENCY ORDER — files with no imports come first, entry point comes last.
2. The "imports" field must list every other project module this file imports (dot-notation, e.g. "utils.helpers").
3. Keep it minimal — only files truly needed.
4. Entry point must be in the files list.
5. Use relative paths only (e.g. "utils/helpers.py", not absolute paths).
6. Standard library modules (os, sys, json, etc.) do NOT go in "dependencies".
7. If the request is a restaurant or pizzeria website, include dedicated pages for the home, menu, table reservation, and online ordering. The reservation and ordering flows must be functional in the first version.

JSON:"""

    try:
        response = model.generate_content(prompt)
        raw = _strip_fences(response.text)
        return json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Planner returned invalid JSON: {e}\nRaw: {response.text[:300]}")
    except Exception as e:
        if _is_rate_limit(e) or _is_transient_model_error(e):
            raise RateLimitError(str(e))
        raise

def _write_generic_web_project(project_dir: Path, description: str) -> dict[str, str]:
    summary = re.sub(r"[`\"']?[A-Za-z]:\\[^\r\n`\"']+[`\"']?", "", description).strip(" .,;:")
    summary = summary[:240] or "Una prima versione completa del tuo progetto web."
    escaped_summary = summary.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    navigation = "<a href='index.html'>Home</a><a href='features.html'>Funzionalita</a><a href='about.html'>Progetto</a><a href='contact.html'>Contatti</a>"
    template = """<!DOCTYPE html><html lang='it'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{title}</title><link rel='stylesheet' href='styles.css'></head><body><header><a class='brand' href='index.html'>Il tuo progetto</a><nav>{navigation}</nav></header><main>{content}</main><footer>Prima versione del progetto</footer><script src='script.js'></script></body></html>"""
    pages = {
        "index.html": template.format(title="Il tuo nuovo sito", navigation=navigation, content=f"<section class='hero'><p class='eyebrow'>Prima versione funzionante</p><h1>Un sito pronto per partire.</h1><p>{escaped_summary}</p><a class='button' href='features.html'>Scopri il progetto</a></section>"),
        "features.html": template.format(title="Funzionalita", navigation=navigation, content="<section><p class='eyebrow'>Funzionalita</p><h1>Tutto l'essenziale, in un unico posto.</h1><div class='grid'><article><h2>Chiaro</h2><p>Contenuti organizzati e facili da esplorare.</p></article><article><h2>Veloce</h2><p>Una base leggera, pronta per crescere.</p></article><article><h2>Responsive</h2><p>Un'esperienza curata su desktop e mobile.</p></article></div></section>"),
        "about.html": template.format(title="Il progetto", navigation=navigation, content=f"<section><p class='eyebrow'>Il progetto</p><h1>Una presenza digitale costruita intorno alla tua idea.</h1><p>{escaped_summary}</p></section>"),
        "contact.html": template.format(title="Contatti", navigation=navigation, content="<section><p class='eyebrow'>Contatti</p><h1>Parliamo del prossimo passo.</h1><form><label>Nome<input type='text' placeholder='Il tuo nome'></label><label>Email<input type='email' placeholder='nome@email.com'></label><label>Messaggio<textarea placeholder='Scrivi qui'></textarea></label><button class='button' type='submit'>Invia</button></form></section>"),
        "styles.css": ":root{font-family:Georgia,serif;color:#18251f;background:#f4f0e8}*{box-sizing:border-box}body{margin:0}header,main,footer{width:min(1100px,calc(100% - 2rem));margin:auto}header{display:flex;justify-content:space-between;align-items:center;padding:1.5rem 0;border-bottom:1px solid #c9c1b5}nav{display:flex;gap:1rem;flex-wrap:wrap}a{color:inherit;text-decoration:none}.brand{font-size:1.3rem;font-weight:bold}.hero,section{padding:7rem 0 5rem;max-width:850px}.eyebrow{color:#a44b2a;text-transform:uppercase;letter-spacing:.12em;font:700 .75rem sans-serif}h1{font-size:clamp(2.5rem,7vw,5.5rem);line-height:1.05;margin:1rem 0}h2{font-size:1.5rem}.button{display:inline-block;background:#a44b2a;color:white;padding:.9rem 1.2rem;margin-top:1rem;border:0;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.grid article{border-top:3px solid #a44b2a;padding:1rem 0}form{display:grid;gap:1rem;max-width:500px}label{display:grid;gap:.4rem;font-family:sans-serif}input,textarea{font:inherit;padding:.8rem;border:1px solid #c9c1b5;background:#fff}textarea{min-height:120px}footer{padding:2rem 0;border-top:1px solid #c9c1b5;font-family:sans-serif}@media(max-width:700px){header{display:block}nav{margin-top:1rem}.hero,section{padding:4rem 0 3rem}.grid{grid-template-columns:1fr}}",
        "script.js": "document.querySelectorAll('form').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); alert('Messaggio pronto per essere collegato al tuo servizio.'); }));",
    }
    for relative_path, content in pages.items():
        full_path = project_dir / relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
    return pages


def _write_pizzeria_web_project(project_dir: Path) -> dict[str, str]:
    """Return a complete static pizzeria website with the requested pages and
    business-facing content. This is an offline fallback that should be used
    when the planner/writer model is unavailable, and it must be substantial
    enough to satisfy the user's pizzeria website request without a blank base.
    """
    navigation = "<a href='index.html'>Home</a><a href='chi_siamo.html'>Chi siamo</a><a href='storia.html'>La nostra storia</a><a href='menu.html'>Menu</a><a href='prenota.html'>Prenota</a><a href='ordina.html'>Ordina</a>"
    template = """<!DOCTYPE html><html lang='it'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>{title} | Forno Vivo</title><link rel='stylesheet' href='styles.css'></head><body><header><a class='brand' href='index.html'>FORNO VIVO</a><nav>{navigation}</nav></header><main>{content}</main><footer>Forno Vivo | Via del Grano 12 | 02 555 0188</footer><script src='script.js'></script></body></html>"""
    pages = {
        "index.html": template.format(title="Pizzeria artigianale", navigation=navigation, content="<section class='hero'><p class='eyebrow'>Pizzeria artigianale</p><h1>Pizza vera, fatta con tempo e fuoco.</h1><p>Impasto a lunga lievitazione, ingredienti italiani e forno caldo ogni sera.</p><div class='actions'><a class='button' href='menu.html'>Guarda il menu</a><a class='button outline' href='prenota.html'>Prenota un tavolo</a></div></section><section class='split'><div><p class='eyebrow'>Questa sera</p><h2>Il tavolo giusto ti aspetta.</h2><p>Prenota online in pochi secondi oppure ordina la tua pizza da asporto.</p></div><div class='notice'><strong>Orari</strong><br>Lun-Dom, 18:30-23:30<br><strong>Asporto</strong><br>Ritiro in circa 20 minuti</div></section><section class='feature-strip'><article><span class='icon'>🔥</span><h3>Forno a legna</h3><p>La nostra pizza nasce nel forno a legna.</p></article><article><span class='icon'>🌾</span><h3>Impasto lento</h3><p>Lievitazione naturale e gusto autentico.</p></article><article><span class='icon'>🍅</span><h3>Ingredienti freschi</h3><p>Pomodoro, mozzarella e basilico ogni giorno.</p></article></section>"),
        "chi_siamo.html": template.format(title="Chi siamo", navigation=navigation, content="<section><p class='eyebrow'>Chi siamo</p><h1>Una pizzeria costruita attorno alle persone.</h1><p>Forno Vivo nasce da una famiglia di pizzaioli e appassionati di cucina semplice, genuina e condivisa.</p><p>La nostra cucina si fonda sulla passione per l'impasto, sul rispetto delle materie prime e sull'idea che una pizza debba riunire tavoli, storie e amicizie.</p><div class='grid'><article><h2>La nostra idea</h2><p>Servire una pizza bella e calda, senza fronzoli ma con cura.</p></article><article><h2>La nostra squadra</h2><p>Un team giovane, attento e guidato da ricette tradizionali.</p></article><article><h2>La nostra promessa</h2><p>Ingredienti freschi, forno a legna e ospitalità sincera.</p></article></div></section>"),
        "storia.html": template.format(title="La nostra storia", navigation=navigation, content="<section><p class='eyebrow'>La nostra storia</p><h1>Da una piccola bottega al forno di tutta la città.</h1><p>Forno Vivo nacque oltre vent'anni fa dal sogno di una famiglia che voleva portare in strada il profumo di una vera pizza fatta in casa.</p><p>Nel tempo il forno ha accolto contadini, studenti, vicini di casa e turisti: ogni locale ha un'antica teglia, ogni ricetta custodisce una memoria di famiglia.</p><p>Oggi la pizzeria continua a lavorare con lievitazione naturale, farine italiane, forno a legna e il piacere di servire tavoli felici.</p></section>"),
        "menu.html": template.format(title="Menu", navigation=navigation, content="<section><p class='eyebrow'>Il menu</p><h1>Classici e idee del giorno.</h1><div class='menu-grid'><article><h2>Margherita <span>8,50 €</span></h2><p>Pomodoro, fiordilatte, basilico</p><button class='add' data-name='Margherita' data-price='8.5'>Aggiungi</button></article><article><h2>Diavola <span>11,00 €</span></h2><p>Pomodoro, fiordilatte, salame piccante</p><button class='add' data-name='Diavola' data-price='11'>Aggiungi</button></article><article><h2>Ortolana <span>12,00 €</span></h2><p>Verdure arrosto, provola affumicata, olio al basilico</p><button class='add' data-name='Ortolana' data-price='12'>Aggiungi</button></article><article><h2>Bufala <span>13,00 €</span></h2><p>Pomodoro, mozzarella di bufala, basilico</p><button class='add' data-name='Bufala' data-price='13'>Aggiungi</button></article></div><p id='cart-status' class='notice'>Il tuo ordine è vuoto.</p><a class='button' href='ordina.html'>Vai all'ordine</a></section>"),
        "prenota.html": template.format(title="Prenota un tavolo", navigation=navigation, content="<section><p class='eyebrow'>Prenotazione</p><h1>Il tuo tavolo, senza telefonate.</h1><form id='booking-form'><label>Nome<input name='name' required placeholder='Il tuo nome'></label><label>Data<input name='date' type='date' required></label><label>Ora<select name='time' required><option value='19:30'>19:30</option><option value='20:30'>20:30</option><option value='21:30'>21:30</option></select></label><label>Persone<input name='guests' type='number' min='1' max='12' value='2' required></label><button class='button' type='submit'>Conferma prenotazione</button></form><p id='booking-status' class='notice' aria-live='polite'></p></section>"),
        "ordina.html": template.format(title="Ordina online", navigation=navigation, content="<section><p class='eyebrow'>Ordina online</p><h1>La tua pizza, pronta quando vuoi.</h1><div id='order-list' class='notice'>Aggiungi prodotti dal <a href='menu.html'>menu</a>.</div><form id='order-form'><label>Nome<input name='name' required placeholder='Il tuo nome'></label><label>Ritiro o consegna<select name='method'><option>Ritiro in pizzeria</option><option>Consegna a domicilio</option></select></label><label>Note<textarea name='notes' placeholder='Citofono, allergie o richieste'></textarea></label><button class='button' type='submit'>Invia ordine</button></form><p id='order-status' class='notice' aria-live='polite'></p></section>"),
        "styles.css": ":root{font-family:Georgia,serif;color:#2b211b;background:#f7f1e7}*{box-sizing:border-box}body{margin:0}header,main,footer{width:min(1100px,calc(100% - 2rem));margin:auto}header{display:flex;justify-content:space-between;align-items:center;padding:1.5rem 0;border-bottom:1px solid #d8cbbb}nav{display:flex;gap:1rem;flex-wrap:wrap}a{color:inherit;text-decoration:none}.brand{font-size:1.3rem;font-weight:bold;letter-spacing:.08em}.hero,section{padding:6rem 0 4rem;max-width:900px}.eyebrow{color:#b34f2c;text-transform:uppercase;letter-spacing:.14em;font:700 .75rem sans-serif}h1{font-size:clamp(2.7rem,7vw,5.5rem);line-height:1.02;margin:1rem 0}h2{font-size:1.45rem}p{font-size:1.1rem;line-height:1.65}.actions{display:flex;gap:1rem;flex-wrap:wrap}.button,.add{display:inline-block;background:#b34f2c;color:#fff;border:0;padding:.9rem 1.2rem;margin-top:1rem;cursor:pointer;font:inherit}.outline{background:transparent;color:#b34f2c;border:1px solid #b34f2c}.split{display:grid;grid-template-columns:1fr 1fr;gap:3rem}.notice{background:#eadfce;padding:1rem;line-height:1.7}.feature-strip{display:grid;grid-template-columns:repeat(3, minmax(160px, 1fr));gap:1rem;margin-top:2rem}.feature-strip article{background:#fffaf3;border:1px solid #d8cbbb;padding:1.5rem}.feature-strip .icon{font-size:1.5rem}.menu-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.menu-grid article{border-top:3px solid #b34f2c;padding:1rem 0}.menu-grid h2{display:flex;justify-content:space-between;gap:1rem}.menu-grid h2 span{white-space:nowrap;color:#b34f2c}form{display:grid;gap:1rem;max-width:520px}label{display:grid;gap:.4rem;font-family:sans-serif}input,select,textarea{font:inherit;padding:.8rem;border:1px solid #d8cbbb;background:#fff}textarea{min-height:110px}footer{padding:2rem 0;border-top:1px solid #d8cbbb;font:14px sans-serif}@media(max-width:700px){header{display:block}nav{margin-top:1rem}.hero,section{padding:4rem 0 3rem}.split,.menu-grid,.feature-strip{grid-template-columns:1fr}.menu-grid h2{display:block}.menu-grid h2 span{display:block;margin-top:.3rem}}",
        "script.js": "const cart=JSON.parse(localStorage.getItem('fornoVivoCart')||'[]'); const save=()=>localStorage.setItem('fornoVivoCart',JSON.stringify(cart)); const render=()=>{const status=document.querySelector('#cart-status'); const list=document.querySelector('#order-list'); if(status) status.textContent=cart.length?`Nel carrello: ${cart.map(item=>item.name).join(', ')} (${cart.reduce((sum,item)=>sum+item.price,0).toFixed(2)} euro)`:\"Il tuo ordine è vuoto.\"; if(list) list.textContent=cart.length?`${cart.map(item=>item.name).join(', ')} | Totale: ${cart.reduce((sum,item)=>sum+item.price,0).toFixed(2)} euro`:\"Il carrello è vuoto: aggiungi prodotti dal menu.\"}; document.querySelectorAll('.add').forEach(button=>button.addEventListener('click',()=>{cart.push({name:button.dataset.name,price:Number(button.dataset.price)});save();render()})); document.querySelector('#booking-form')?.addEventListener('submit',event=>{event.preventDefault();document.querySelector('#booking-status').textContent='Richiesta ricevuta: ti confermeremo presto il tavolo.'}); document.querySelector('#order-form')?.addEventListener('submit',event=>{event.preventDefault();if(!cart.length){document.querySelector('#order-status').textContent='Aggiungi almeno una pizza prima di inviare l\'ordine.';return}document.querySelector('#order-status').textContent='Ordine ricevuto: la pizzeria ti contatterà per confermare.';}); render();",
    }
    for relative_path, content in pages.items():
        full_path = project_dir / relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
    return pages


def _write_fallback_web_project(project_dir: Path, description: str = "") -> dict[str, str]:
    """Create a complete multi-page landing site without relying on the Gemini model."""
    if description and _is_pizzeria_request(description):
        return _write_pizzeria_web_project(project_dir)
    if description and not _is_jarvis_request(description):
        return _write_generic_web_project(project_dir, description)

    files = {
        "index.html": """<!DOCTYPE html>
<html lang=\"it\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>JARVIS | Il tuo assistente AI</title>
    <meta name=\"description\" content=\"JARVIS è l'assistente AI per desktop che ti aiuta a lavorare, automatizzare compiti e organizzare la tua giornata.\" />
    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />
    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />
    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" />
    <link rel=\"stylesheet\" href=\"styles.css\" />
  </head>
  <body>
    <header class=\"site-header\">
      <div class=\"container nav-wrap\">
        <a class=\"brand\" href=\"index.html\"><span class=\"brand-mark\">J</span><span>JARVIS</span></a>
        <nav class=\"main-nav\" aria-label=\"Menu principale\">
          <a href=\"index.html\" class=\"active\">Home</a>
          <a href=\"features.html\">Funzioni</a>
          <a href=\"download.html\">Download</a>
          <a href=\"about.html\">Chi siamo</a>
          <a href=\"contact.html\">Contatti</a>
          <a href=\"download.html\" class=\"button small\">Scarica</a>
        </nav>
      </div>
    </header>

    <main>
      <section class=\"hero\">
        <div class=\"container hero-grid\">
          <div class=\"hero-copy\">
            <span class=\"eyebrow\">AI desktop companion</span>
            <h1>Trasforma il tuo computer in un assistente intelligente.</h1>
            <p>JARVIS combina automazione, assistenza intelligente e organizzazione personale in un unico strumento sempre attivo sul tuo desktop. Risparmia tempo, riduci stress e fai di più ogni giorno.</p>
            <div class=\"cta-row\">
              <a href=\"download.html\" class=\"button primary\">Scarica JARVIS</a>
              <a href=\"features.html\" class=\"button secondary\">Scopri le funzioni</a>
            </div>
            <ul class=\"mini-trust\">
              <li>✅ Più produttività</li>
              <li>✅ Supporto costante</li>
              <li>✅ Interfaccia semplice</li>
            </ul>
          </div>
          <div class=\"hero-visual\">
            <div class=\"dashboard-card\">
              <div class=\"dashboard-header\"><span class=\"dot red\"></span><span class=\"dot yellow\"></span><span class=\"dot green\"></span></div>
              <div class=\"dashboard-body\">
                <div class=\"signal-bar\"><span></span><span></span><span></span><span></span></div>
                <div class=\"assistant-panel\">
                  <p class=\"label\">JARVIS</p>
                  <h3>Buongiorno, Gabriele.</h3>
                  <ul>
                    <li>✅ 4 task completati</li>
                    <li>✅ Meteo aggiornata</li>
                    <li>✅ Promemoria creati</li>
                  </ul>
                </div>
                <div class=\"quick-actions\"><button>Ricerca</button><button>File</button><button>App</button></div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class=\"stats band\">
        <div class=\"container stats-grid\">
          <div><strong>3x</strong><span>più produttivo</span></div>
          <div><strong>10+</strong><span>funzioni automatizzate</span></div>
          <div><strong>24/7</strong><span>supporto intelligente</span></div>
          <div><strong>1 click</strong><span>per agire subito</span></div>
        </div>
      </section>

      <section class=\"section\">
        <div class=\"container\">
          <div class=\"section-heading\">
            <span class=\"eyebrow\">Perché JARVIS</span>
            <h2>Un assistente che fa davvero la differenza.</h2>
          </div>
          <div class=\"card-grid three\">
            <article class=\"feature-card\"><div class=\"icon\">⚡</div><h3>Automazione intelligente</h3><p>Elimina compiti ripetitivi e risparmia tempo prezioso sulla tua giornata.</p></article>
            <article class=\"feature-card\"><div class=\"icon\">🧠</div><h3>AI personalizzata</h3><p>Interagisci con un assistente che capisce il tuo contesto e le tue preferenze.</p></article>
            <article class=\"feature-card\"><div class=\"icon\">🔐</div><h3>Controllo semplice</h3><p>Gestisci file, app, browser e reminder senza passare da mille programmi.</p></article>
          </div>
        </div>
      </section>
    </main>

    <footer class=\"site-footer\">
      <div class=\"container footer-wrap\">
        <p>© <span id=\"year\"></span> JARVIS</p>
        <div class=\"footer-links\"><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"contact.html\">Contatti</a></div>
      </div>
    </footer>
    <script src=\"script.js\"></script>
  </body>
</html>
""",
        "features.html": """<!DOCTYPE html>
<html lang=\"it\">
  <head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>Funzioni JARVIS</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" /><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin /><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" /><link rel=\"stylesheet\" href=\"styles.css\" /></head>
  <body>
    <header class=\"site-header\"><div class=\"container nav-wrap\"><a class=\"brand\" href=\"index.html\"><span class=\"brand-mark\">J</span><span>JARVIS</span></a><nav class=\"main-nav\"><a href=\"index.html\">Home</a><a href=\"features.html\" class=\"active\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"about.html\">Chi siamo</a><a href=\"contact.html\">Contatti</a><a href=\"download.html\" class=\"button small\">Scarica</a></nav></div></header>
    <main>
      <section class=\"page-hero\"><div class=\"container narrow center\"><span class=\"eyebrow\">Le funzioni principali</span><h1>Tutto ciò di cui hai bisogno in un solo assistente.</h1></div></section>
      <section class=\"section\"><div class=\"container card-grid three\"><article class=\"feature-card large\"><div class=\"icon\">📁</div><h3>Gestione file</h3><p>Organizza documenti, trova file e crea flussi di lavoro più ordinati.</p></article><article class=\"feature-card large\"><div class=\"icon\">🌐</div><h3>Ricerca web</h3><p>Cerca informazioni e contenuti utili senza aprire centinaia di schede.</p></article><article class=\"feature-card large\"><div class=\"icon\">🔔</div><h3>Promemoria</h3><p>Tieni sotto controllo appuntamenti, obiettivi e priorità quotidiane.</p></article><article class=\"feature-card large\"><div class=\"icon\">💬</div><h3>Aiuto personale</h3><p>Ottieni supporto rapido per domande, idee e organizzazione del lavoro.</p></article><article class=\"feature-card large\"><div class=\"icon\">🧩</div><h3>Integrazione app</h3><p>Connetti le app che usi di più e lascia che JARVIS ti guidi.</p></article><article class=\"feature-card large\"><div class=\"icon\">🛠️</div><h3>Automazioni</h3><p>Crea routine automatiche per compiti ripetitivi e lavori giornalieri.</p></article></div></section>
    </main>
    <footer class=\"site-footer\"><div class=\"container footer-wrap\"><p>© <span id=\"year\"></span> JARVIS</p><div class=\"footer-links\"><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"contact.html\">Contatti</a></div></div></footer>
    <script src=\"script.js\"></script>
  </body>
</html>
""",
        "download.html": """<!DOCTYPE html>
<html lang=\"it\">
  <head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>Scarica JARVIS</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" /><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin /><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" /><link rel=\"stylesheet\" href=\"styles.css\" /></head>
  <body>
    <header class=\"site-header\"><div class=\"container nav-wrap\"><a class=\"brand\" href=\"index.html\"><span class=\"brand-mark\">J</span><span>JARVIS</span></a><nav class=\"main-nav\"><a href=\"index.html\">Home</a><a href=\"features.html\">Funzioni</a><a href=\"download.html\" class=\"active\">Download</a><a href=\"about.html\">Chi siamo</a><a href=\"contact.html\">Contatti</a><a href=\"download.html\" class=\"button small\">Scarica</a></nav></div></header>
    <main>
      <section class=\"page-hero\"><div class=\"container narrow center\"><span class=\"eyebrow\">Disponibile subito</span><h1>Scarica JARVIS oggi stesso.</h1><p>Un prototipo completo pronto a migliorare la tua produttività.</p></div></section>
      <section class=\"section\"><div class=\"container download-layout\"><div class=\"download-card feature-card\"><span class=\"pill\">Versione 1.0</span><h2>JARVIS Desktop</h2><ul class=\"check-list compact\"><li>Installazione semplice</li><li>Assistente personale sul desktop</li><li>Automazioni pratiche</li><li>Interfaccia intuitiva</li></ul><a href=\"#\" class=\"button primary large\">Scarica per Windows</a><small>Compatibile con Windows 10 e 11</small></div><div class=\"download-info\"><div class=\"info-box\"><strong>Installa in pochi minuti</strong><p>Scarica, esegui il setup e diventa subito più produttivo.</p></div><div class=\"info-box\"><strong>Design pensato per il lavoro</strong><p>Ogni funzione è stata concepita per essere utile, veloce e semplice.</p></div></div></div></section>
    </main>
    <footer class=\"site-footer\"><div class=\"container footer-wrap\"><p>© <span id=\"year\"></span> JARVIS</p><div class=\"footer-links\"><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"contact.html\">Contatti</a></div></div></footer>
    <script src=\"script.js\"></script>
  </body>
</html>
""",
        "about.html": """<!DOCTYPE html>
<html lang=\"it\">
  <head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>Chi siamo | JARVIS</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" /><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin /><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" /><link rel=\"stylesheet\" href=\"styles.css\" /></head>
  <body>
    <header class=\"site-header\"><div class=\"container nav-wrap\"><a class=\"brand\" href=\"index.html\"><span class=\"brand-mark\">J</span><span>JARVIS</span></a><nav class=\"main-nav\"><a href=\"index.html\">Home</a><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"about.html\" class=\"active\">Chi siamo</a><a href=\"contact.html\">Contatti</a><a href=\"download.html\" class=\"button small\">Scarica</a></nav></div></header>
    <main>
      <section class=\"page-hero\"><div class=\"container narrow center\"><span class=\"eyebrow\">La nostra missione</span><h1>Rendere l'intelligenza artificiale utile, semplice e accessibile.</h1></div></section>
      <section class=\"section\"><div class=\"container split-layout\"><div><h2>JARVIS nasce per semplificare la vita digitale.</h2><p>Crediamo che gli strumenti intelligenti non debbano essere complicati. Vogliamo dare alle persone un assistente sempre presente, utile e facile da usare.</p><p>Per questo JARVIS unisce automazioni, informazioni e supporto personale in un'unica esperienza pensata per il desktop.</p></div><div class=\"feature-visual\"><div class=\"fancy-panel\"><p class=\"label\">Vision</p><div class=\"list-rows\"><span>✔ AI accessibile</span><span>✔ Produttività reale</span><span>✔ Esperienza semplificata</span></div></div></div></div></section>
    </main>
    <footer class=\"site-footer\"><div class=\"container footer-wrap\"><p>© <span id=\"year\"></span> JARVIS</p><div class=\"footer-links\"><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"contact.html\">Contatti</a></div></div></footer>
    <script src=\"script.js\"></script>
  </body>
</html>
""",
        "contact.html": """<!DOCTYPE html>
<html lang=\"it\">
  <head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>Contatti | JARVIS</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" /><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin /><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" /><link rel=\"stylesheet\" href=\"styles.css\" /></head>
  <body>
    <header class=\"site-header\"><div class=\"container nav-wrap\"><a class=\"brand\" href=\"index.html\"><span class=\"brand-mark\">J</span><span>JARVIS</span></a><nav class=\"main-nav\"><a href=\"index.html\">Home</a><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"about.html\">Chi siamo</a><a href=\"contact.html\" class=\"active\">Contatti</a><a href=\"download.html\" class=\"button small\">Scarica</a></nav></div></header>
    <main>
      <section class=\"page-hero\"><div class=\"container narrow center\"><span class=\"eyebrow\">Contattaci</span><h1>Hai domande? Siamo qui per aiutarti.</h1></div></section>
      <section class=\"section\"><div class=\"container contact-layout\"><div class=\"contact-card\"><h2>Info e supporto</h2><ul class=\"contact-list\"><li><strong>Email:</strong> hello@jarvis-ai.example</li><li><strong>Telefono:</strong> +39 02 555 0147</li><li><strong>Orari:</strong> Lun - Ven, 9:00 - 18:00</li></ul></div><form class=\"contact-form\"><label>Nome<input type=\"text\" placeholder=\"Il tuo nome\" /></label><label>Email<input type=\"email\" placeholder=\"nome@email.com\" /></label><label>Messaggio<textarea rows=\"5\" placeholder=\"Scrivi qui il tuo messaggio...\"></textarea></label><button type=\"submit\" class=\"button primary\">Invia</button></form></div></section>
    </main>
    <footer class=\"site-footer\"><div class=\"container footer-wrap\"><p>© <span id=\"year\"></span> JARVIS</p><div class=\"footer-links\"><a href=\"features.html\">Funzioni</a><a href=\"download.html\">Download</a><a href=\"contact.html\">Contatti</a></div></div></footer>
    <script src=\"script.js\"></script>
  </body>
</html>
""",
        "styles.css": """:root { --bg:#060816; --bg-alt:#0d1224; --panel:rgba(18,24,43,.9); --text:#edf3ff; --muted:#b6c1d9; --primary:#7c9cff; --primary-strong:#5d7dff; --accent:#61e3c9; --line:rgba(159,171,205,.18); } *{box-sizing:border-box} body{margin:0;font-family:'Inter',sans-serif;background:radial-gradient(circle at top left, rgba(124,156,255,.22), transparent 30%), radial-gradient(circle at top right, rgba(97,227,201,.14), transparent 24%), var(--bg); color:var(--text); line-height:1.6} a{text-decoration:none;color:inherit} .container{width:min(1120px, calc(100% - 2rem));margin:0 auto} .site-header{position:sticky;top:0;backdrop-filter:blur(18px);background:rgba(7,11,22,.7);border-bottom:1px solid var(--line)} .nav-wrap{display:flex;align-items:center;justify-content:space-between;gap:1rem;min-height:76px} .brand{display:inline-flex;align-items:center;gap:.7rem;font-weight:800;letter-spacing:.08em} .brand-mark{display:inline-flex;align-items:center;justify-content:center;width:2rem;height:2rem;border-radius:.6rem;background:linear-gradient(135deg,var(--primary),var(--accent));color:#081120;font-weight:900;box-shadow:0 0 18px rgba(124,156,255,.55)} .main-nav{display:flex;align-items:center;gap:1.2rem}.main-nav a{color:var(--muted);font-weight:500}.main-nav a:hover,.main-nav a.active{color:var(--text)} .button{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:.9rem 1.4rem;border:1px solid transparent;font-weight:700}.button.primary{background:linear-gradient(135deg,var(--primary),var(--primary-strong));color:white;box-shadow:0 16px 38px rgba(93,125,255,.35)} .button.secondary{border-color:rgba(124,156,255,.35);background:rgba(124,156,255,.08);color:var(--text)} .button.small{padding:.7rem 1rem;font-size:.9rem}.button.large{padding:1rem 1.8rem}.hero{padding:5.5rem 0 3rem}.hero-grid,.split-layout,.download-layout,.contact-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:2.5rem;align-items:center}.hero-copy h1,.page-hero h1,.section-heading h2,.split-layout h2{margin:0 0 1rem;line-height:1.05;letter-spacing:-.06em}.hero-copy h1{font-size:clamp(2.8rem,5vw,5rem)}.page-hero h1{font-size:clamp(2rem,3vw,3.15rem)} .eyebrow{display:inline-block;margin-bottom:1rem;padding:.38rem .72rem;border:1px solid rgba(124,156,255,.25);border-radius:999px;background:rgba(124,156,255,.09);color:#dfe8ff;font-size:.72rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.hero-copy p,.split-layout p,.feature-card p,.info-box p,.contact-card li{color:var(--muted)} .cta-row{display:flex;flex-wrap:wrap;gap:1rem;margin-top:1.8rem}.mini-trust{display:flex;flex-wrap:wrap;gap:1rem 1.5rem;margin:1.5rem 0 0;padding:0;list-style:none;color:var(--text);font-weight:600}.dashboard-card{width:min(100%,460px);padding:1rem;border:1px solid var(--line);border-radius:2rem;background:linear-gradient(180deg,rgba(16,26,45,.96),rgba(11,18,33,.9));box-shadow:0 24px 70px rgba(6,10,20,.75)} .dashboard-header{display:flex;align-items:center;gap:.5rem;padding:0 .2rem .9rem}.dot{width:.8rem;height:.8rem;border-radius:50%}.dot.red{background:#ff6d6d}.dot.yellow{background:#ffc857}.dot.green{background:#6bdd8d}.dashboard-body{background:rgba(7,12,25,.8);border:1px solid var(--line);border-radius:1.4rem;padding:1.4rem}.signal-bar{display:flex;align-items:end;gap:.4rem;height:2.2rem;margin-bottom:1.2rem}.signal-bar span{display:block;width:18%;border-radius:999px;background:linear-gradient(180deg,var(--accent),var(--primary))}.signal-bar span:nth-child(1){height:32%}.signal-bar span:nth-child(2){height:56%}.signal-bar span:nth-child(3){height:78%}.signal-bar span:nth-child(4){height:100%}.assistant-panel{background:rgba(20,29,51,.9);border:1px solid var(--line);border-radius:1.2rem;padding:1rem}.label{margin:0 0 .5rem;color:var(--accent);font-size:.8rem;letter-spacing:.12em;text-transform:uppercase;font-weight:800}.assistant-panel h3{margin:0 0 .9rem;font-size:1.7rem}.assistant-panel ul{margin:0;padding-left:1.1rem;color:var(--muted)} .quick-actions{display:flex;gap:.7rem;margin-top:1rem}.quick-actions button{flex:1;border:1px solid var(--line);background:rgba(124,156,255,.08);color:var(--text);border-radius:.9rem;padding:.7rem .9rem}.band{background:rgba(12,17,29,.8);border-top:1px solid var(--line);border-bottom:1px solid var(--line)} .stats-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;padding:2rem 0}.stats-grid div{display:flex;flex-direction:column;align-items:center;text-align:center;gap:.3rem}.stats-grid strong{font-size:clamp(1.8rem,2vw,2.4rem)}.stats-grid span{color:var(--muted)}.section{padding:5rem 0}.alt-section{background:rgba(11,17,29,.75);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.section-heading{margin-bottom:2rem;text-align:center}.card-grid{display:grid;gap:1.5rem}.card-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.feature-card{background:rgba(20,29,51,.7);border:1px solid var(--line);border-radius:1.5rem;padding:1.6rem;box-shadow:0 18px 35px rgba(4,7,14,.2)}.icon{width:3.2rem;height:3.2rem;display:grid;place-items:center;border-radius:1rem;background:linear-gradient(135deg, rgba(124,156,255,.18), rgba(97,227,201,.12));font-size:1.5rem;margin-bottom:1rem}.feature-card h3{margin:0 0 .6rem}.page-hero{padding:4.5rem 0 2.25rem}.narrow{max-width:760px}.center{text-align:center}.check-list{list-style:none;padding:0;margin:1.25rem 0 0;display:grid;gap:.8rem;color:var(--text)}.check-list li{position:relative;padding-left:1.7rem}.check-list li::before{content:'✓';position:absolute;left:0;top:0;color:var(--accent);font-weight:800}.download-card{min-height:100%}.pill{display:inline-block;margin-bottom:.8rem;padding:.4rem .8rem;border-radius:999px;background:rgba(97,227,201,.12);border:1px solid rgba(97,227,201,.24);color:var(--accent);font-size:.75rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.download-info{display:grid;gap:1rem}.info-box{background:rgba(20,29,51,.7);border:1px solid var(--line);border-radius:1.3rem;padding:1.25rem 1.3rem}.info-box strong{display:block;margin-bottom:.4rem;font-size:1.15rem}.contact-card,.contact-form{background:rgba(20,29,51,.7);border:1px solid var(--line);border-radius:1.5rem;padding:1.5rem}.contact-list{list-style:none;margin:1rem 0 0;padding:0;display:grid;gap:.9rem}.contact-form{display:grid;gap:1rem}.contact-form label{display:grid;gap:.45rem;font-weight:600}.contact-form input,.contact-form textarea{width:100%;border:1px solid var(--line);border-radius:.95rem;background:rgba(9,15,26,.8);color:var(--text);padding:.9rem 1rem}.site-footer{padding:1.5rem 0 2rem;border-top:1px solid var(--line)}.footer-wrap{display:flex;align-items:center;justify-content:space-between;gap:1rem;color:var(--muted)}.footer-links{display:flex;gap:1rem;flex-wrap:wrap}@media (max-width: 900px){ .hero-grid,.split-layout,.download-layout,.contact-layout,.card-grid.three,.stats-grid{grid-template-columns:1fr} }""",
        "script.js": """document.addEventListener('DOMContentLoaded', () => { const year = document.getElementById('year'); if (year) year.textContent = new Date().getFullYear(); });""",
    }

    written = {}
    for relative_path, content in files.items():
        full_path = project_dir / relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding='utf-8')
        written[relative_path] = content

    return written


def _write_file(
    file_info: dict,
    project_description: str,
    all_files: list[dict],
    language: str,
    project_dir: Path,
    already_written: dict[str, str],
) -> str:
    model = _get_model(MODEL_WRITER)

    file_path = file_info["path"]
    file_desc = file_info.get("description", "")
    file_imports = file_info.get("imports", [])

    file_list = "\n".join(
        f"  [{i+1}] {f['path']}: {f.get('description', '')}"
        for i, f in enumerate(all_files)
    )

    dependency_context = ""
    for dep_dotted in file_imports:
        dep_path = dep_dotted.replace(".", "/") + ".py"
        if dep_path in already_written:
            code_snippet = already_written[dep_path][:2000]
            dependency_context += f"\n\n--- {dep_path} (you must import from this) ---\n{code_snippet}"

    lang_rules = ""
    if language.lower() == "python":
        lang_rules = """
Python-specific rules:
- Use type hints for all function signatures.
- Add docstrings for all public functions and classes.
- Use if __name__ == "__main__": guard in the entry point.
- For relative imports within the project, use: from utils.helpers import foo  (match the project structure exactly).
- Do NOT use implicit relative imports (from . import ...) unless it's a proper package with __init__.py.
- If this is a package subdirectory, create __init__.py files where needed."""
    elif language.lower() in ("javascript", "typescript", "js", "ts"):
        lang_rules = """
JS/TS-specific rules:
- Use ES modules (import/export), not CommonJS (require).
- Add JSDoc comments for all exported functions.
- Handle promise rejections with try/catch in async functions."""

    prompt = f"""You are a senior {language} developer writing production-quality code for a real project.

Project goal: {project_description}

Complete project file structure (in dependency order):
{file_list}

{f"Dependencies this file must import from other project files:{dependency_context}" if dependency_context else ""}

Your task: Write the complete, working code for: {file_path}
Purpose of this file: {file_desc}
{f"This file imports from: {', '.join(file_imports)}" if file_imports else "This file has no project-internal imports."}

{lang_rules}

General rules:
- Output ONLY raw code. Absolutely no explanation, no markdown, no triple backticks.
- Write COMPLETE, RUNNABLE code — no placeholders, no "# TODO", no "pass" stubs.
- Every import must either be from the standard library, listed dependencies, or the project files shown above.
- Match import paths EXACTLY to the file paths in the project structure (e.g. if file is "utils/helpers.py", import as "from utils.helpers import ...").
- Use proper error handling (try/except) where I/O or network calls are made.
- The code must work correctly when the project entry point is run from the project root directory.

Code for {file_path}:"""

    try:
        response = model.generate_content(prompt)
        code = _strip_fences(response.text)

        full_path = project_dir / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(code, encoding="utf-8")

        print(f"[DevAgent] ✅ Written: {file_path} ({len(code)} chars)")
        return code

    except Exception as e:
        if _is_rate_limit(e) or _is_transient_model_error(e):
            raise RateLimitError(str(e))
        raise

def _install_dependencies(dependencies: list[str], project_dir: Path) -> str:
    if not dependencies:
        return "No external dependencies."

    to_install = []
    for dep in dependencies:
        pkg_name = re.split(r"[>=<!]", dep)[0].strip()
        result = subprocess.run(
            [sys.executable, "-m", "pip", "show", pkg_name],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            to_install.append(dep)
        else:
            print(f"[DevAgent] ✓ Already installed: {pkg_name}")

    if not to_install:
        return f"All dependencies already installed: {', '.join(dependencies)}"

    print(f"[DevAgent] 📦 Installing: {to_install}")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install"] + to_install,
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=120, cwd=str(project_dir)
        )
        if result.returncode == 0:
            return f"Installed: {', '.join(to_install)}"
        return f"Install warning (non-fatal): {result.stderr[:200]}"
    except subprocess.TimeoutExpired:
        return "Dependency install timed out (non-fatal)."
    except Exception as e:
        return f"Install error (non-fatal): {e}"

def _open_vscode(project_dir: Path) -> bool:
    vscode_candidates = [
        "code",
        rf"C:\Users\{Path.home().name}\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd",
        r"C:\Program Files\Microsoft VS Code\bin\code.cmd",
    ]
    for cmd in vscode_candidates:
        try:
            subprocess.Popen(
                [cmd, str(project_dir)],
                shell=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
            )
            time.sleep(1.5)
            print(f"[DevAgent] 💻 VSCode opened: {project_dir}")
            return True
        except Exception:
            continue
    return False

def _run_project(run_command: str, project_dir: Path, timeout: int = 30) -> str:
    print(f"[DevAgent] 🚀 Running: {run_command}")
    try:
        parts = shlex.split(run_command, posix=False)
        if not parts:
            return "PROCESS_EXIT_CODE: 1\nRun error: empty command"
        if parts[0].lower() in {"python", "python3", "py"}:
            parts[0] = sys.executable

        result = subprocess.run(
            parts,
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=timeout,
            cwd=str(project_dir)
        )

        stdout = result.stdout.strip()
        stderr = result.stderr.strip()

        combined_parts = []
        combined_parts.append(f"PROCESS_EXIT_CODE: {result.returncode}")
        if stdout:
            combined_parts.append(f"STDOUT:\n{stdout}")
        if stderr:
            combined_parts.append(f"STDERR:\n{stderr}")

        return "\n\n".join(combined_parts) if combined_parts else "Ran with no output."

    except subprocess.TimeoutExpired:
        return f"Timed out after {timeout}s — long-running app (server/GUI) is likely working."
    except FileNotFoundError as e:
        return f"PROCESS_EXIT_CODE: 127\nCommand not found: {e}"
    except Exception as e:
        return f"PROCESS_EXIT_CODE: 1\nRun error: {e}"

def _try_auto_install(error_output: str, project_dir: Path) -> bool:
    """ModuleNotFoundError varsa eksik paketi otomatik kurmaya çalışır."""
    pattern = re.compile(
        r"No module named ['\"]([a-zA-Z0-9_\-\.]+)['\"]", re.IGNORECASE
    )
    match = pattern.search(error_output)
    if not match:
        return False

    pkg = match.group(1).replace("_", "-").split(".")[0]
    print(f"[DevAgent] 🔧 Auto-installing missing package: {pkg}")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", pkg],
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=60, cwd=str(project_dir)
        )
        return result.returncode == 0
    except Exception:
        return False

def _fix_files(
    error_output: str,
    project_description: str,
    all_files: list[dict],
    file_codes: dict[str, str],
    language: str,
    project_dir: Path,
    entry_point: str,
) -> dict[str, str]:

    model = _get_model(MODEL_PLANNER)

    error_file, error_line = _parse_traceback(error_output, list(file_codes.keys()))
    error_type = _classify_error(error_output)

    files_to_fix: list[str] = []

    if error_file:
        files_to_fix.append(error_file)
        if error_type == "import_error":
            for fi in all_files:
                if error_file.replace("/", ".").replace(".py", "") in fi.get("imports", []):
                    p = fi["path"]
                    if p not in files_to_fix:
                        files_to_fix.append(p)
    else:
        files_to_fix.append(entry_point)

    updated_codes: dict[str, str] = {}

    for fix_path in files_to_fix:
        current_code = file_codes.get(fix_path, "")

        other_ctx = ""
        for fp, code in file_codes.items():
            if fp != fix_path and code:
                snippet = code[:1500] + ("..." if len(code) > 1500 else "")
                other_ctx += f"\n--- {fp} ---\n{snippet}\n"

        line_hint = f"\nError appears to be near line {error_line} in this file." if (
            error_line and fix_path == error_file
        ) else ""

        prompt = f"""You are an expert {language} debugger. Fix the broken file below.

Project goal: {project_description}

All project files:
{chr(10).join(f"  - {f['path']}: {f.get('description', '')}" for f in all_files)}

Other files for context (read-only — fix only the target file):
{other_ctx[:3500]}

File to fix: {fix_path}{line_hint}
Error type: {error_type}

Error output:
{error_output[:2500]}

Current (broken) code:
{current_code}

Rules:
- Output ONLY the complete fixed code. No explanation, no markdown, no backticks.
- Fix ALL errors visible in the error output.
- Keep all existing correct logic — do not remove working features.
- Ensure import paths match the actual project file structure exactly.
- Do NOT introduce new bugs or remove error handling.

Fixed code for {fix_path}:"""

        try:
            response = model.generate_content(prompt)
            fixed = _strip_fences(response.text)

            full_path = project_dir / fix_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(fixed, encoding="utf-8")

            updated_codes[fix_path] = fixed
            print(f"[DevAgent] 🔧 Fixed: {fix_path}")

        except Exception as e:
            if _is_rate_limit(e) or _is_transient_model_error(e):
                raise RateLimitError(str(e))
            print(f"[DevAgent] ⚠️ Could not fix {fix_path}: {e}")

    return updated_codes

def _build_project(
    description: str,
    language: str,
    project_name: str,
    timeout: int,
    speak=None,
    player=None,
) -> str:

    def log(msg: str):
        print(f"[DevAgent] {msg}")
        if player:
            player.write_log(f"[DevAgent] {msg}")

    project_dir = _project_directory(description, project_name)
    proj_name = project_dir.name or "jarvis_project"
    project_dir.mkdir(parents=True, exist_ok=True)

    log("Planning project structure...")
    try:
        plan = _plan_project(description, language)
    except RateLimitError as e:
        msg = f"Planning stopped because the model provider rate-limited the request: {e}. No preset fallback website was generated."
        if speak:
            speak(msg)
        return msg
    except ValueError as e:
        msg = f"Planning failed: {e}. No preset fallback website was generated; the project needs a real model-backed code write path."
        if speak:
            speak(msg)
        return msg
    except Exception as e:
        msg = f"Planning failed: {e}. No preset fallback website was generated; the project needs a real model-backed code write path."
        if speak:
            speak(msg)
        return msg

    files        = plan.get("files", [])
    entry_point  = plan.get("entry_point", "main.py")
    run_command  = plan.get("run_command", f"python {entry_point}")
    dependencies = plan.get("dependencies", [])

    log(f"Project: {proj_name} | Files: {len(files)} | Entry: {entry_point}")

    def _dep_sort_key(fi: dict) -> int:
        return len(fi.get("imports", []))

    sorted_files = sorted(files, key=_dep_sort_key)

    file_codes: dict[str, str] = {}

    for file_info in sorted_files:
        file_path = file_info.get("path", "")
        if not file_path:
            continue

        log(f"Writing {file_path}...")
        for attempt in range(2):
            try:
                code = _write_file(
                    file_info=file_info,
                    project_description=description,
                    all_files=files,
                    language=language,
                    project_dir=project_dir,
                    already_written=file_codes,
                )
                file_codes[file_path] = code
                time.sleep(0.4)
                break
            except RateLimitError as e:
                msg = f"Writing stopped because the model provider rate-limited the request: {e}. No preset fallback website was generated; the project needs a real model-backed code write path."
                if speak:
                    speak(msg)
                log(msg)
                return msg
            except Exception as e:
                log(f"Failed to write {file_path}: {e}")
                msg = f"Writing failed: {e}. No preset fallback website was generated; the project needs a real model-backed code write path."
                if speak:
                    speak(msg)
                return msg

    if not file_codes:
        msg = "I could not write any project files, sir."
        if speak: speak(msg)
        return msg

    if dependencies:
        install_result = _install_dependencies(dependencies, project_dir)
        log(install_result)

    _open_vscode(project_dir)

    last_output   = ""
    auto_installs = 0  

    for attempt in range(1, MAX_FIX_ATTEMPTS + 1):
        log(f"Running project (attempt {attempt}/{MAX_FIX_ATTEMPTS})...")
        last_output = _run_project(run_command, project_dir, timeout)
        log(f"Output preview: {last_output[:150]}")

        if not _has_error(last_output, run_command):
            msg = (
                f"Project '{proj_name}' is working, sir. "
                f"Built in {attempt} attempt{'s' if attempt > 1 else ''}. "
                f"Saved to: {project_dir}"
            )
            if speak: speak(msg)
            return f"{msg}\n\nOutput:\n{last_output}"

        if attempt == MAX_FIX_ATTEMPTS:
            break

        error_type = _classify_error(last_output)
        if error_type == "dependency_error" and auto_installs < 3:
            installed = _try_auto_install(last_output, project_dir)
            if installed:
                auto_installs += 1
                log("Missing dependency installed, retrying...")
                time.sleep(1)
                continue

        log(f"Fixing errors (type: {error_type})...")
        try:
            updated = _fix_files(
                error_output=last_output,
                project_description=description,
                all_files=files,
                file_codes=file_codes,
                language=language,
                project_dir=project_dir,
                entry_point=entry_point,
            )
            file_codes.update(updated)
            time.sleep(1)
        except RateLimitError:
            msg = "Rate limit reached during fix. Project saved, check it manually in VSCode."
            if speak: speak(msg)
            return msg
        except Exception as e:
            log(f"Fix step failed: {e}")

    msg = (
        f"I couldn't fully fix '{proj_name}' after {MAX_FIX_ATTEMPTS} attempts, sir. "
        f"Project is saved at {project_dir} — open it in VSCode and check manually."
    )
    if speak: speak(msg)
    return f"{msg}\n\nLast error:\n{last_output[:600]}"


def dev_agent(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
    speak=None,
) -> str:
    p            = parameters or {}
    description  = p.get("description", "").strip()
    language     = p.get("language", "python").strip()
    project_name = p.get("project_name", "").strip()
    try:
        timeout = max(1, min(int(p.get("timeout", 30)), 300))
    except (TypeError, ValueError):
        timeout = 30

    if not description:
        return "Please describe the project you want me to build, sir."

    return _build_project(
        description  = description,
        language     = language,
        project_name = project_name,
        timeout      = timeout,
        speak        = speak,
        player       = player,
    )